import 'package:strength_app/domain/entities/exercise.dart';
import 'package:strength_app/domain/entities/workout.dart';

class ExerciseData {
  ExerciseData._();

  static const Workout legsWorkout = Workout(
    id: 'legs',
    name: '臀腿训练',
    description: '针对跑者的核心力量训练',
    estimatedMinutes: 15,
    exercises: [
      Exercise(
        id: 'squat',
        name: '深蹲',
        description: '双脚与肩同宽，膝盖弯曲至大腿与地面平行，背部挺直',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '大腿前侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'deadlift',
        name: '硬拉',
        description: '双手持重物，向前弯腰，背部挺直，感受大腿后侧拉伸',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '大腿后侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'lunge',
        name: '箭步蹲',
        description: '向前跨一步，膝盖弯曲，身体向下蹲，保持平衡',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['大腿前侧', '大腿后侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'side_lunge',
        name: '侧蹲',
        description: '向一侧跨步，膝盖弯曲，身体向下蹲，感受大腿内侧拉伸',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['大腿内侧', '大腿外侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'calf_raise',
        name: '提踵',
        description: '双脚站立，踮起脚尖，保持几秒后放下，锻炼小腿',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['小腿'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'glute_bridge',
        name: '臀桥',
        description: '仰卧屈膝，向上推臀部至身体成直线',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '核心'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'single_leg_deadlift',
        name: '单腿硬拉',
        description: '单腿站立，向前弯腰，另一条腿向后抬起，保持平衡',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '大腿后侧', '核心'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'leg_press',
        name: '保加利亚分腿蹲',
        description: '后脚搭在沙发或椅子上，前脚下蹲至大腿与地面平行',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['大腿前侧', '臀部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.legs,
      ),
    ],
  );

  static const Workout coreWorkout = Workout(
    id: 'core',
    name: '核心训练',
    description: '增强躯干稳定性，提升跑步姿态控制',
    estimatedMinutes: 12,
    exercises: [
      Exercise(
        id: 'plank',
        name: '平板支撑',
        description: '前臂撑地，身体保持一条直线，收紧腹部',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '肩部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'side_plank',
        name: '侧平板支撑',
        description: '单侧前臂撑地，身体侧面保持一条直线',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 15,
        targetMuscles: ['核心', '腰部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'dead_bug',
        name: '死虫式',
        description: '仰卧，双臂伸向天花板，双腿抬起呈90度，交替伸展',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '髋屈肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'bird_dog',
        name: '鸟狗式',
        description: '四点跪姿，同时伸展对侧手臂和腿，保持平衡',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '臀部', '背部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'mountain_climber',
        name: '登山者',
        description: '俯卧撑姿势，交替将膝盖拉向胸部',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 15,
        targetMuscles: ['核心', '肩部', '腿部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'russian_twist',
        name: '俄罗斯转体',
        description: '坐姿，双脚离地，上半身左右旋转',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '腰部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.core,
      ),
    ],
  );

  static const Workout upperBodyWorkout = Workout(
    id: 'upper_body',
    name: '上肢训练',
    description: '增强上肢力量，提升摆臂效率',
    estimatedMinutes: 18,
    exercises: [
      Exercise(
        id: 'push_up',
        name: '俯卧撑',
        description: '双手撑地，身体保持一条直线，屈臂下降再推起',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['胸部', '三头肌', '肩部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.upperBody,
      ),
      Exercise(
        id: 'pull_up',
        name: '钻石俯卧撑',
        description: '双手靠拢呈钻石形，屈臂下降再推起，强化三头肌',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['三头肌', '胸部'],
        difficulty: Difficulty.advanced,
        category: ExerciseCategory.upperBody,
      ),
      Exercise(
        id: 'dumbbell_press',
        name: '哑铃推举',
        description: '双手持哑铃，从肩部向上推起至手臂伸直',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['肩部', '三头肌'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.upperBody,
      ),
      Exercise(
        id: 'bicep_curl',
        name: '哑铃弯举',
        description: '双手持哑铃，屈肘将哑铃举向肩部',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['二头肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.upperBody,
      ),
      Exercise(
        id: 'tricep_dip',
        name: '三头肌撑体',
        description: '背对椅子，双手撑在椅边，屈臂下降再推起',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['三头肌', '胸部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.upperBody,
      ),
      Exercise(
        id: 'bent_over_row',
        name: '俯身划船',
        description: '俯身，双手持哑铃，向后拉起至胸部两侧',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['背部', '二头肌'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.upperBody,
      ),
      Exercise(
        id: 'lateral_raise',
        name: '侧平举',
        description: '双手持哑铃，向两侧抬起至肩平',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['肩部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.upperBody,
      ),
      Exercise(
        id: 'front_raise',
        name: '前平举',
        description: '双手持哑铃，向前抬起至肩平',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['肩部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.upperBody,
      ),
    ],
  );

  static const Workout fullBodyWorkout = Workout(
    id: 'full_body',
    name: '全身训练',
    description: '综合训练，提升整体体能',
    estimatedMinutes: 20,
    exercises: [
      Exercise(
        id: 'burpee',
        name: '波比跳',
        description: '下蹲→跳脚→俯卧撑→收腿→跳起，连续动作',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 30,
        targetMuscles: ['全身'],
        difficulty: Difficulty.advanced,
        category: ExerciseCategory.fullBody,
      ),
      Exercise(
        id: 'kettlebell_swing',
        name: '哑铃摆动',
        description: '双手持哑铃一端，用臀部发力向前摆动至肩平',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['臀部', '背部', '核心'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.fullBody,
      ),
      Exercise(
        id: 'thruster',
        name: '深蹲推举',
        description: '深蹲起立时顺势将哑铃推举过头',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['腿部', '肩部', '核心'],
        difficulty: Difficulty.advanced,
        category: ExerciseCategory.fullBody,
      ),
      Exercise(
        id: 'clean_and_press',
        name: '深蹲跳',
        description: '深蹲后爆发力跳起，落地时缓冲屈膝',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 30,
        targetMuscles: ['腿部', '臀部', '核心'],
        difficulty: Difficulty.advanced,
        category: ExerciseCategory.fullBody,
      ),
      Exercise(
        id: 'man_maker',
        name: '人肉制造机',
        description: '俯卧撑→划船→深蹲→推举，连续动作',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 30,
        targetMuscles: ['全身'],
        difficulty: Difficulty.advanced,
        category: ExerciseCategory.fullBody,
      ),
      Exercise(
        id: 'jumping_jack',
        name: '开合跳',
        description: '跳起时双脚分开，双手在头顶击掌',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['全身'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.fullBody,
      ),
    ],
  );

  static const Workout warmupWorkout = Workout(
    id: 'warmup',
    name: '跑前热身',
    description: '激活心肺、提升体温、动态拉伸主要肌群',
    estimatedMinutes: 12,
    exercises: [
      Exercise(
        id: 'warmup_jumping_jack',
        name: '开合跳',
        description: '跳起时双脚分开，双手在头顶击掌，全身激活',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['全身'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'high_knees',
        name: '高抬腿',
        description: '原地跑步，膝盖尽量抬高至腰部，激活髋屈肌',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['髋屈肌', '大腿前侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'butt_kicks',
        name: '后踢腿',
        description: '原地跑步，脚后跟尽量踢向臀部，拉伸大腿前侧',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['大腿前侧', '腘绳肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'grapevine',
        name: '侧向交叉步',
        description: '侧向移动，双腿交替交叉，激活髋关节',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['髋关节', '大腿内侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'lunge_with_twist',
        name: '动态弓步转体',
        description: '向前弓步，上身向弓步侧旋转，拉伸髋屈肌和胸椎',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['髋屈肌', '胸椎', '核心'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'front_leg_swings',
        name: '前后摆腿',
        description: '单手扶墙，腿部前后摆动，拉伸腘绳肌',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['腘绳肌', '髋屈肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'side_leg_swings',
        name: '侧向摆腿',
        description: '单手扶墙，腿部左右摆动，拉伸大腿内侧',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['大腿内侧', '大腿外侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'hip_circles',
        name: '髋关节绕环',
        description: '单腿站立，另一条腿画圈，活动髋关节',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['髋关节'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'worlds_greatest_stretch',
        name: '最伟大拉伸',
        description: '弓步→手肘触地→转体伸手，全身动态拉伸',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['全身'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'calf_walks',
        name: '小腿行走',
        description: '踮脚向前行走，拉伸小腿和跟腱',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['小腿', '跟腱'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'arm_circles',
        name: '手臂绕环',
        description: '双臂伸直，前后画圈，活动肩关节',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['肩部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
      Exercise(
        id: 'torso_twists',
        name: '躯干旋转',
        description: '双脚分开，双臂平举，左右旋转躯干，激活核心',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['核心', '腰部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.warmup,
      ),
    ],
  );

  static const Workout stretchWorkout = Workout(
    id: 'stretch',
    name: '跑后拉伸',
    description: '放松紧张肌群、促进乳酸代谢、提升柔韧性',
    estimatedMinutes: 20,
    exercises: [
      // 下肢拉伸（核心）
      Exercise(
        id: 'standing_quad_stretch',
        name: '站立股四头肌拉伸',
        description: '单腿站立，另一条腿向后弯曲，用手抓住脚踝拉向臀部',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['大腿前侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'standing_hamstring_stretch',
        name: '站立腘绳肌拉伸',
        description: '单腿伸直放在椅子上，身体前倾感受大腿后侧拉伸',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['大腿后侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'standing_calf_stretch',
        name: '站立小腿拉伸',
        description: '面向墙壁，一腿前一腿后，后腿脚跟踩地感受小腿拉伸',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['小腿'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'kneeling_hip_flexor_stretch',
        name: '髋屈肌弓步拉伸',
        description: '单膝跪地，另一腿向前弓步，身体前倾拉伸髋屈肌',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['髋屈肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'pigeon_pose',
        name: '鸽子式',
        description: '一腿弯曲在前，另一腿伸直在后，身体前倾拉伸臀部',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['臀部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'butterfly_stretch',
        name: '蝴蝶式',
        description: '坐姿，双脚掌相对，膝盖向两侧下压拉伸大腿内侧',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['大腿内侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'supine_figure_four',
        name: '仰卧4字拉伸',
        description: '仰卧，一腿弯曲跨过另一腿，双手抱住大腿后侧拉向胸部',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['臀部', '梨状肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'wide_legged_forward_fold',
        name: '坐姿宽腿前屈',
        description: '坐姿，双腿向两侧打开，身体前倾拉伸大腿内侧和下背部',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['大腿内侧', '下背部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      // 躯干/核心拉伸
      Exercise(
        id: 'cat_cow',
        name: '猫牛式',
        description: '四点跪姿，交替弓背和塌腰，活动脊柱',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['脊柱', '核心'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'supine_spinal_twist',
        name: '仰卧脊柱扭转',
        description: '仰卧，一腿弯曲跨过身体，头部转向对侧，拉伸脊柱',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['脊柱', '腰部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'cobra_stretch',
        name: '眼镜蛇式',
        description: '俯卧，双手撑地将上半身抬起，拉伸腹部和髋屈肌',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['腹部', '髋屈肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'childs_pose',
        name: '婴儿式',
        description: '跪坐，身体前倾趴地，双臂向前伸展，全身放松',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['全身'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      // 上肢/肩颈拉伸
      Exercise(
        id: 'neck_side_stretch',
        name: '颈部侧屈拉伸',
        description: '坐姿，一手将头部轻轻拉向一侧，拉伸颈部侧面',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 5,
        targetMuscles: ['颈部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'upper_trapezius_stretch',
        name: '上斜方肌拉伸',
        description: '一手绕过头顶触摸对侧耳朵，轻轻拉向一侧',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 5,
        targetMuscles: ['肩部', '颈部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'doorway_pec_stretch',
        name: '胸肌门框拉伸',
        description: '站在门框处，手臂弯曲90度贴在门框上，身体前倾拉伸胸肌',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 5,
        targetMuscles: ['胸部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'cross_body_shoulder_stretch',
        name: '肩部后伸拉伸',
        description: '一臂伸直横过胸前，另一手将其拉向身体',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 5,
        targetMuscles: ['肩部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
      Exercise(
        id: 'overhead_triceps_stretch',
        name: '过头三头肌拉伸',
        description: '一臂向上弯曲，手触摸对侧肩胛骨，另一手将其向后推',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 5,
        targetMuscles: ['三头肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.stretch,
      ),
    ],
  );

  static List<Workout> get allWorkouts => [
        warmupWorkout,
        legsWorkout,
        coreWorkout,
        upperBodyWorkout,
        fullBodyWorkout,
        stretchWorkout,
      ];
}
