import 'package:strength_app/domain/entities/exercise.dart';
import 'package:strength_app/domain/entities/workout.dart';

class ExerciseData {
  ExerciseData._();

  static const Workout legsWorkout = Workout(
    id: 'legs',
    name: '臀腿训练',
    description: '针对跑者的核心力量训练',
    estimatedMinutes: 15,
    exercises: [
      Exercise(
        id: 'squat',
        name: '深蹲',
        description: '双脚与肩同宽，膝盖弯曲至大腿与地面平行，背部挺直',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '大腿前侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'deadlift',
        name: '硬拉',
        description: '双手持重物，向前弯腰，背部挺直，感受大腿后侧拉伸',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '大腿后侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'lunge',
        name: '箭步蹲',
        description: '向前跨一步，膝盖弯曲，身体向下蹲，保持平衡',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['大腿前侧', '大腿后侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'side_lunge',
        name: '侧蹲',
        description: '向一侧跨步，膝盖弯曲，身体向下蹲，感受大腿内侧拉伸',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['大腿内侧', '大腿外侧'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'calf_raise',
        name: '提踵',
        description: '双脚站立，踮起脚尖，保持几秒后放下，锻炼小腿',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['小腿'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'glute_bridge',
        name: '臀桥',
        description: '仰卧屈膝，向上推臀部至身体成直线',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '核心'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'single_leg_deadlift',
        name: '单腿硬拉',
        description: '单腿站立，向前弯腰，另一条腿向后抬起，保持平衡',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['臀部', '大腿后侧', '核心'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.legs,
      ),
      Exercise(
        id: 'leg_press',
        name: '腿举',
        description: '仰卧屈膝，向上推双腿至伸直，感受大腿前侧发力',
        imagePath: '',
        durationSeconds: 60,
        restSeconds: 5,
        targetMuscles: ['大腿前侧', '臀部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.legs,
      ),
    ],
  );

  static const Workout coreWorkout = Workout(
    id: 'core',
    name: '核心训练',
    description: '增强躯干稳定性，提升跑步姿态控制',
    estimatedMinutes: 12,
    exercises: [
      Exercise(
        id: 'plank',
        name: '平板支撑',
        description: '前臂撑地，身体保持一条直线，收紧腹部',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '肩部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'side_plank',
        name: '侧平板支撑',
        description: '单侧前臂撑地，身体侧面保持一条直线',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 15,
        targetMuscles: ['核心', '腰部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'dead_bug',
        name: '死虫式',
        description: '仰卧，双臂伸向天花板，双腿抬起呈90度，交替伸展',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '髋屈肌'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'bird_dog',
        name: '鸟狗式',
        description: '四点跪姿，同时伸展对侧手臂和腿，保持平衡',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '臀部', '背部'],
        difficulty: Difficulty.beginner,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'mountain_climber',
        name: '登山者',
        description: '俯卧撑姿势，交替将膝盖拉向胸部',
        imagePath: '',
        durationSeconds: 30,
        restSeconds: 15,
        targetMuscles: ['核心', '肩部', '腿部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.core,
      ),
      Exercise(
        id: 'russian_twist',
        name: '俄罗斯转体',
        description: '坐姿，双脚离地，上半身左右旋转',
        imagePath: '',
        durationSeconds: 45,
        restSeconds: 15,
        targetMuscles: ['核心', '腰部'],
        difficulty: Difficulty.intermediate,
        category: ExerciseCategory.core,
      ),
    ],
  );

  static List<Workout> get allWorkouts => [legsWorkout, coreWorkout];
}
