import 'package:runner_app/models/exercise.dart';
import 'package:runner_app/models/workout_type.dart';
import 'package:runner_app/models/workout.dart';

/// Pre-set exercise data for the Runner Training app.
///
/// Contains all exercises organized by workout type:
/// - [warmupExercises]: 12 pre-run dynamic warmup movements
/// - [stretchExercises]: 17 post-run stretching exercises
/// - [strengthExercises]: 18 strength training exercises (3 sections)

// ============================================================
// Warmup exercises (12) - Pre-run dynamic热身
// ============================================================

const List<Exercise> warmupExercises = [
  Exercise(
    id: 'warmup_01',
    name: '开合跳',
    description: '全身激活运动，双腿交替开合跳跃，双臂举过头顶',
    localVideoPath: 'videos/warmup/jumping_jacks.mp4',
    imagePath: 'images/warmup/jumping_jacks.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['legs', 'core'],
    category: ExerciseCategory.fullBody,
  ),
  Exercise(
    id: 'warmup_02',
    name: '高抬腿',
    description: '髋屈肌激活，原地抬高双腿，膝盖接近腰部',
    localVideoPath: 'videos/warmup/high_knees.mp4',
    imagePath: 'images/warmup/high_knees.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hipFlexors'],
    category: ExerciseCategory.fullBody,
  ),
  Exercise(
    id: 'warmup_03',
    name: '后踢腿',
    description: '股四头肌和腘绳肌激活，脚跟踢向臀部',
    localVideoPath: 'videos/warmup/butt_kicks.mp4',
    imagePath: 'images/warmup/butt_kicks.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['quads', 'hamstrings'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'warmup_04',
    name: '侧向交叉步',
    description: '髋关节活动度提升，侧向移动时双腿交叉',
    localVideoPath: 'videos/warmup/carioca.mp4',
    imagePath: 'images/warmup/carioca.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hips'],
    category: ExerciseCategory.fullBody,
  ),
  Exercise(
    id: 'warmup_05',
    name: '动态弓步转体',
    description: '髋屈肌和胸椎激活，弓步同时上半身转向前腿侧',
    localVideoPath: 'videos/warmup/lunge_twist.mp4',
    imagePath: 'images/warmup/lunge_twist.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hips', 'thoracicSpine'],
    category: ExerciseCategory.fullBody,
  ),
  Exercise(
    id: 'warmup_06',
    name: '直腿踢',
    description: '腘绳肌动态拉伸，保持腿部伸直向前踢',
    localVideoPath: 'videos/warmup/straight_leg_kicks.mp4',
    imagePath: 'images/warmup/straight_leg_kicks.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hamstrings'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'warmup_07',
    name: '侧摆腿',
    description: '髋内收肌和外展肌激活，侧向摆动双腿',
    localVideoPath: 'videos/warmup/lateral_leg_swings.mp4',
    imagePath: 'images/warmup/lateral_leg_swings.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hips', 'adductors'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'warmup_08',
    name: '髋关节绕环',
    description: '髋关节活动度提升，单腿支撑画圈',
    localVideoPath: 'videos/warmup/hip_circles.mp4',
    imagePath: 'images/warmup/hip_circles.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hipsMobility'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'warmup_09',
    name: '最伟大拉伸',
    description: '全身动态复合动作，弓步+胸椎旋转+腘绳肌拉伸',
    localVideoPath: 'videos/warmup/worlds_greatest_stretch.mp4',
    imagePath: 'images/warmup/worlds_greatest_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['fullBodyDynamic'],
    category: ExerciseCategory.fullBody,
  ),
  Exercise(
    id: 'warmup_10',
    name: '小腿拉伸',
    description: '小腿和跟腱动态拉伸，弓步推墙',
    localVideoPath: 'videos/warmup/calf_stretch.mp4',
    imagePath: 'images/warmup/calf_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['calves', 'achilles'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'warmup_11',
    name: '手臂绕环',
    description: '肩关节活动度提升，双臂画圈旋转',
    localVideoPath: 'videos/warmup/arm_circles.mp4',
    imagePath: 'images/warmup/arm_circles.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['shoulders'],
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'warmup_12',
    name: '躯干旋转',
    description: '核心激活，站立时左右旋转躯干',
    localVideoPath: 'videos/warmup/torso_rotations.mp4',
    imagePath: 'images/warmup/torso_rotations.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['coreActivation'],
    category: ExerciseCategory.core,
  ),
];

// ============================================================
// Stretch exercises (17) - Post-run stretching
// ============================================================

const List<Exercise> stretchExercises = [
  // 下肢拉伸 (8)
  Exercise(
    id: 'stretch_01',
    name: '站立股四头肌拉伸',
    description: '站立，将脚后跟拉向臀部，感受大腿前侧拉伸',
    localVideoPath: 'videos/stretch/standing_quad_stretch.mp4',
    imagePath: 'images/stretch/standing_quad_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['quads'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'stretch_02',
    name: '站立腘绳肌拉伸',
    description: '单腿伸直放在前方，俯身感受大腿后侧拉伸',
    localVideoPath: 'videos/stretch/standing_hamstring_stretch.mp4',
    imagePath: 'images/stretch/standing_hamstring_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hamstrings'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'stretch_03',
    name: '小腿后侧拉伸',
    description: '面向墙壁，后腿伸直，脚跟压地',
    localVideoPath: 'videos/stretch/calf_stretch.mp4',
    imagePath: 'images/stretch/calf_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['calves'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'stretch_04',
    name: '髋屈肌弓步拉伸',
    description: '弓步姿势，后腿膝盖着地，感受髋前拉伸',
    localVideoPath: 'videos/stretch/hip_flexor_lunge.mp4',
    imagePath: 'images/stretch/hip_flexor_lunge.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hipFlexors'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'stretch_05',
    name: '鸽子式臀肌拉伸',
    description: '前腿弯曲置于身前，后腿伸直后方，俯身拉伸',
    localVideoPath: 'videos/stretch/pigeon_pose.mp4',
    imagePath: 'images/stretch/pigeon_pose.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['glutes'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'stretch_06',
    name: '坐姿蝴蝶式',
    description: '脚底相对，膝盖向外压，身体前倾',
    localVideoPath: 'videos/stretch/butterfly_stretch.mp4',
    imagePath: 'images/stretch/butterfly_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['adductors'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'stretch_07',
    name: '仰卧4字拉伸',
    description: '仰卧，一脚踝放另一膝盖上，双手拉大腿向胸',
    localVideoPath: 'videos/stretch/supine_figure_four.mp4',
    imagePath: 'images/stretch/supine_figure_four.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['piriformis'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'stretch_08',
    name: '坐姿宽腿前屈',
    description: '双腿分开坐直，身体向前俯，双臂伸直',
    localVideoPath: 'videos/stretch/seated_wide_leg_forward_fold.mp4',
    imagePath: 'images/stretch/seated_wide_leg_forward_fold.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['hamstrings', 'adductors'],
    category: ExerciseCategory.lowerBody,
  ),
  // 躯干/核心拉伸 (4)
  Exercise(
    id: 'stretch_09',
    name: '猫牛式',
    description: '四肢着地，交替弓背和塌腰，脊柱逐节活动',
    localVideoPath: 'videos/stretch/cat_cow.mp4',
    imagePath: 'images/stretch/cat_cow.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['spineMobility'],
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'stretch_10',
    name: '仰卧脊柱扭转',
    description: '仰卧，屈膝倒向一侧，头部转向反方向',
    localVideoPath: 'videos/stretch/supine_spinal_twist.mp4',
    imagePath: 'images/stretch/supine_spinal_twist.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['spine'],
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'stretch_11',
    name: '眼镜蛇式',
    description: '俯卧，双手支撑抬起上半身，拉伸腹部和髋屈肌',
    localVideoPath: 'videos/stretch/cobra_pose.mp4',
    imagePath: 'images/stretch/cobra_pose.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['abs', 'hipFlexors'],
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'stretch_12',
    name: '婴儿式',
    description: '跪坐，身体前俯手臂伸直，完全放松',
    localVideoPath: 'videos/stretch/child_pose.mp4',
    imagePath: 'images/stretch/child_pose.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['fullRelax'],
    category: ExerciseCategory.core,
  ),
  // 上肢/肩颈拉伸 (5)
  Exercise(
    id: 'stretch_13',
    name: '颈部侧屈拉伸',
    description: '坐直，头向一侧倾斜，手轻压头部',
    localVideoPath: 'videos/stretch/neck_lateral_flexion.mp4',
    imagePath: 'images/stretch/neck_lateral_flexion.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['neck'],
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'stretch_14',
    name: '上斜方肌拉伸',
    description: '一手身后，头向对侧拉，感受颈部到肩部拉伸',
    localVideoPath: 'videos/stretch/upper_trapezius_stretch.mp4',
    imagePath: 'images/stretch/upper_trapezius_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['trapezius'],
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'stretch_15',
    name: '胸肌门框拉伸',
    description: '手臂靠在门框上，身体前移感受胸部拉伸',
    localVideoPath: 'videos/stretch/pec_doorway_stretch.mp4',
    imagePath: 'images/stretch/pec_doorway_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['pecs'],
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'stretch_16',
    name: '肩部后伸拉伸',
    description: '双手背后交握，向后伸直手臂打开肩关节',
    localVideoPath: 'videos/stretch/posterior_shoulder_stretch.mp4',
    imagePath: 'images/stretch/posterior_shoulder_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['shoulders'],
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'stretch_17',
    name: '过头三头肌拉伸',
    description: '手臂过头弯曲，另一手轻推肘部向头部',
    localVideoPath: 'videos/stretch/overhead_tricep_stretch.mp4',
    imagePath: 'images/stretch/overhead_tricep_stretch.png',
    durationSeconds: 45,
    restSeconds: 5,
    targetMuscles: ['triceps'],
    category: ExerciseCategory.upperBody,
  ),
];

// ============================================================
// Strength exercises (18) - 3 sections
// ============================================================

const List<Exercise> strengthExercises = [
  // 板块A：臀腿力量 (6)
  Exercise(
    id: 'strength_01',
    name: '深蹲',
    description: '股四头肌和臀大肌训练，双脚与肩同宽，臀部后坐下蹲',
    localVideoPath: 'videos/strength/squat.mp4',
    imagePath: 'images/strength/squat.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['quads', 'glutes'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'strength_02',
    name: '弓步蹲',
    description: '单腿稳定性训练，大步向前下蹲，前后腿各呈90度',
    localVideoPath: 'videos/strength/lunge.mp4',
    imagePath: 'images/strength/lunge.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['singleLeg', 'quads', 'glutes'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'strength_03',
    name: '单腿硬拉',
    description: '腘绳肌和平衡能力，单腿站立俯身触碰地面',
    localVideoPath: 'videos/strength/single_leg_deadlift.mp4',
    imagePath: 'images/strength/single_leg_deadlift.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['hamstrings', 'balance'],
    difficulty: Difficulty.advanced,
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'strength_04',
    name: '侧弓步',
    description: '髋内收肌和外展肌训练，向侧方迈步下蹲',
    localVideoPath: 'videos/strength/side_lunge.mp4',
    imagePath: 'images/strength/side_lunge.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['adductors', 'abductors'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'strength_05',
    name: '提踵',
    description: '小腿和跟腱力量训练，踮起脚尖后缓慢放下',
    localVideoPath: 'videos/strength/calf_raise.mp4',
    imagePath: 'images/strength/calf_raise.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['calves', 'achilles'],
    category: ExerciseCategory.lowerBody,
  ),
  Exercise(
    id: 'strength_06',
    name: '臀桥',
    description: '臀大肌和核心训练，仰卧屈膝抬臀至身体呈直线',
    localVideoPath: 'videos/strength/glute_bridge.mp4',
    imagePath: 'images/strength/glute_bridge.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['glutes', 'core'],
    category: ExerciseCategory.lowerBody,
  ),
  // 板块B：核心力量 (6)
  Exercise(
    id: 'strength_07',
    name: '平板支撑',
    description: '核心稳定性训练，前臂支撑身体呈直线',
    localVideoPath: 'videos/strength/plank.mp4',
    imagePath: 'images/strength/plank.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['coreStability'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'strength_08',
    name: '死虫式',
    description: '对侧伸展和核心控制，仰卧交替伸展对侧肢体',
    localVideoPath: 'videos/strength/dead_bug.mp4',
    imagePath: 'images/strength/dead_bug.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['coreControl', 'abs'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'strength_09',
    name: '登山者',
    description: '核心和心肺结合训练，俯卧交替拉膝向胸',
    localVideoPath: 'videos/strength/mountain_climbers.mp4',
    imagePath: 'images/strength/mountain_climbers.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['core', 'cardio'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'strength_10',
    name: '俄罗斯转体',
    description: '腹斜肌训练，坐姿身体后仰旋转双臂',
    localVideoPath: 'videos/strength/russian_twist.mp4',
    imagePath: 'images/strength/russian_twist.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['obliques'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'strength_11',
    name: '仰卧抬腿',
    description: '下腹部训练，仰卧双腿并拢抬至与地面45度',
    localVideoPath: 'videos/strength/lying_leg_raise.mp4',
    imagePath: 'images/strength/lying_leg_raise.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['lowerAbs'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'strength_12',
    name: '鸟狗式',
    description: '核心和平衡训练，四肢着地交替伸展对侧手臂和腿',
    localVideoPath: 'videos/strength/bird_dog.mp4',
    imagePath: 'images/strength/bird_dog.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['core', 'balance'],
    category: ExerciseCategory.core,
  ),
  // 板块C：上肢力量 (6)
  Exercise(
    id: 'strength_13',
    name: '俯卧撑',
    description: '胸肌、肩部和三头肌训练，身体保持直线上下',
    localVideoPath: 'videos/strength/push_up.mp4',
    imagePath: 'images/strength/push_up.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['chest', 'shoulders', 'triceps'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'strength_14',
    name: '三头肌撑体',
    description: '三头肌孤立训练，背靠椅子，双手支撑抬起身体后屈肘',
    localVideoPath: 'videos/strength/tricep_dips.mp4',
    imagePath: 'images/strength/tricep_dips.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['triceps'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'strength_15',
    name: '超人式',
    description: '下背部、臀部和后肩训练，俯卧同时抬起双臂双腿',
    localVideoPath: 'videos/strength/superman.mp4',
    imagePath: 'images/strength/superman.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['lowerBack', 'glutes', 'rearShoulder'],
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'strength_16',
    name: '侧卧撑',
    description: '腹斜肌和肩部训练，侧身前臂支撑身体抬升',
    localVideoPath: 'videos/strength/side_plank.mp4',
    imagePath: 'images/strength/side_plank.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['obliques', 'shoulders'],
    difficulty: Difficulty.intermediate,
    category: ExerciseCategory.core,
  ),
  Exercise(
    id: 'strength_17',
    name: '墙壁天使',
    description: '肩胛稳定性训练，背靠墙双臂做天使翅膀动作',
    localVideoPath: 'videos/strength/wall_angels.mp4',
    imagePath: 'images/strength/wall_angels.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['scapularStability'],
    category: ExerciseCategory.upperBody,
  ),
  Exercise(
    id: 'strength_18',
    name: '哑铃/水瓶弯举',
    description: '二头肌训练，手持哑铃或水瓶交替弯举',
    localVideoPath: 'videos/strength/bicep_curls.mp4',
    imagePath: 'images/strength/bicep_curls.png',
    durationSeconds: 60,
    restSeconds: 5,
    targetMuscles: ['biceps'],
    category: ExerciseCategory.upperBody,
  ),
];

/// Complete exercise registry organized by section.
class ExerciseData {
  ExerciseData._();

  /// All warmup exercises (12)
  static const List<Exercise> warmup = warmupExercises;

  /// All stretch exercises (17)
  static const List<Exercise> stretch = stretchExercises;

  /// All strength exercises (18)
  static const List<Exercise> strength = strengthExercises;

  /// All exercises combined (47 total)
  static List<Exercise> allExercises() {
    return [...warmup, ...stretch, ...strength];
  }

  /// Get exercises for a specific section of strength training.
  static List<Exercise> strengthSection(int sectionIndex) {
    switch (sectionIndex) {
      case 0: // 板块A: 臀腿力量
        return strength.sublist(0, 6);
      case 1: // 板块B: 核心力量
        return strength.sublist(6, 12);
      case 2: // 板块C: 上肢力量
        return strength.sublist(12, 18);
      default:
        return strength;
    }
  }

  /// All predefined workout plans.
  static const List<Workout> allWorkouts = [
    Workout(
      id: 'warmup',
      name: '跑前动态热身',
      description: '激活心肺、提升体温、动态拉伸主要肌群',
      type: WorkoutType.warmup,
      estimatedMinutes: 12,
      exercises: warmupExercises,
      coverImage: 'images/covers/warmup.png',
    ),
    Workout(
      id: 'stretch',
      name: '跑后拉伸',
      description: '放松紧张肌群、促进恢复、提升柔韧性',
      type: WorkoutType.stretch,
      estimatedMinutes: 25,
      exercises: stretchExercises,
      coverImage: 'images/covers/stretch.png',
    ),
    Workout(
      id: 'strength',
      name: '力量训练',
      description: '增强肌力、改善跑姿、预防损伤',
      type: WorkoutType.strength,
      estimatedMinutes: 45,
      exercises: strengthExercises,
      coverImage: 'images/covers/strength.png',
      difficulty: Difficulty.intermediate,
    ),
  ];
}
